name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 22.x]
        package-manager: [npm, pnpm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        if: matrix.package-manager == 'pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ matrix.package-manager }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        shell: bash
        run: |
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npm run lint
          else
            pnpm run lint
          fi
      - name: Build project
        shell: bash
        run: |
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npm run build
          else
            pnpm run build
          fi

      - name: Run tests
        shell: bash
        run: |
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npm run test:ci
          else
            pnpm run test:ci
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next/
          retention-days: 7

  # Additional job for multi-Node testing (only on main branch)
  # test-node-versions:
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  #   strategy:
  #     matrix:
  #       node-version: ["20", "22"]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "pnpm"

  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: latest

  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile

  #     - name: Run tests
  #       run: pnpm run test:ci

  #     - name: Build project
  #       run: pnpm run build
