name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 22.x]
        package-manager: [npm, pnpm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        if: matrix.package-manager == 'pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ matrix.package-manager }}

      - name: Install dependencies
        shell: bash
        run: |
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npm install
          else
            pnpm install --frozen-lockfile
          fi

      - name: Run ESLint
        shell: bash
        run: |
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npm run lint
          else
            pnpm run lint
          fi

      - name: Build project
        shell: bash
        run: |
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npm run build
          else
            pnpm run build
          fi

      - name: Run tests
        shell: bash
        run: |
          if [ "${{ matrix.package-manager }}" = "npm" ]; then
            npm test
          else
            pnpm test
          fi

      - name: Upload build artifacts
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '22.x' && matrix.package-manager == 'pnpm'
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next/
